### ISSUE TITLE
suggestion: take url as path to package.json

### ISSUE THREAD

**Issue by bcullman** [guyellis/packcomp#14]
if I could point to package.json files directly on github, it would save me time from downloading and maintaining the repos locally.

**Comment by guyellis** [comment]
@bcullman you're thinking of the raw link right? So something like this: https://raw.githubusercontent.com/guyellis/packcomp/master/package.json

And your exec syntax would be...

```shell
packcomp https://raw.githubusercontent.com/guyellis/packcomp/master/package.json https://raw.githubusercontent.com/guyellis/<some-other-repo>/master/package.json
```

...right?

And you'd also be able to mix those params with local files as well of course.

**Comment by bcullman** [comment]
Yes, and yes. :)

**Comment by guyellis** [comment]
@bcullman this is now version `1.2.0`

**Comment by bcullman** [comment]
💯 👍 Thank you @guyellis!
