### ISSUE TITLE
provide transpose ability

### ISSUE THREAD

**Issue by bcullman** [guyellis/packcomp#16]
The use case in the following: 

I have used the filter capability to look for just a single dependency, so my table length is shallow. But I am trying to review that dependency across 30+ repositories, making the table width deep.

In this case, it would be great if I could transpose the results and see the dependancies across the top and the repos along the side. 

Perhaps something like this could be useful:
https://gist.github.com/femto113/1784503#file-transpose-js

**Comment by guyellis** [comment]
@bcullman good idea. I've added this and published it as `1.3.0`

Question: The filter doesn't work for me. How are you using it? I don't want to "fix" the filter if it's working.

**Comment by bcullman** [comment]
@guyellis - I use the filter like this:

```
packcomp.js  -f "react" repo1/ repo2/
```

**Comment by bcullman** [comment]
Thanks for the re-write on this... your transpose works much better than the PR i submitted. ;)
